CREATE TABLE SCHOOL_CLASS
(
  SCHOOL_CLASS_ID SERIAL PRIMARY KEY NOT NULL,
  GRADE           SMALLINT           NOT NULL,
  LETTER          VARCHAR(2)         NOT NULL,
  YEAR            INT                NOT NULL,
  TEACHER_ID      BIGINT,
  FOREIGN KEY (TEACHER_ID) REFERENCES HEAD_TEACHER (TEACHER_ID)
);
