CREATE TABLE PUPIL
(
  PUPIL_ID  BIGINT       NOT NULL,
  CLASS_ID  BIGINT,
  FULL_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (PUPIL_ID),
  FOREIGN KEY (CLASS_ID) REFERENCES SCHOOL_CLASS (SCHOOL_CLASS_ID)
);
