@startuml
'skinparam linetype polyline
'skinparam linetype ortho
left to right direction


namespace userservice {
  class User {
    + login
    + password
  }

  class Principal {
  }

  class Teacher {
    + name
    + passportNumber
    + phoneNumber
    + email
    + status
    + salary
    + bonus
  }

  class Parent {
    + name
    + phoneNumber
    + email
  }

  class Pupil {
    + name
    + age
    + grade
    + phoneNumber
    + email
  }

  class Address {
    + city
    + street
    + house
    + apartment
    + zipCode
  }

  User <|- Principal
  User <|-- Teacher
  User <|-- Parent
  User <|-- Pupil
  Principal "1" o- "1" Address : lives by >
  Pupil "1" o- "1" Address : lives by >
  Parent "1" o- "1" Address : lives by >
  Teacher "1" o-- "1" Address : lives by >
  Pupil "many" -l- "many" Parent: \n\thas\n >
}


together {

  namespace scheduleservice  {
    class userservice.Teacher {
        + name
    }

    class Schedule {
        + year
    }

    class Lesson {
        + date
    }

    Schedule "1" *-l> "many" Lesson : \ncontains\n
  }

  namespace curriculumservice {
    class Curriculum {
        + grade
    }

    class Course {
        + lessonCount
    }

    class Subject {
        + name
    }

    Curriculum "one" *-u> "many" Course : \ncontains\n
    Course "one" *-u> "one" Subject : \ncontains\n
  }
}



together {
namespace schoolregisterservice {
  class HomeWork {
      + description
  }

  class Mark {
      + value
  }
}


namespace schoolclassservice {
  class SchoolClass {
      + letter
      + grade
      + year
  }
}
}




schoolclassservice .-> userservice  : gets info about teachers
schoolclassservice .-> userservice  : gets info about pupils
schoolregisterservice .-> userservice  : gets info about pupils
scheduleservice .-> userservice : gets info about teachers
schoolregisterservice .-l> scheduleservice  : gets info about lessons
scheduleservice .-> curriculumservice : gets info about courses
scheduleservice .-r> schoolclassservice : gets info about classes

@enduml
