@startuml
class Principal {

}

class Teacher {
    + firstname
    + lastname
}

class Pupil {
    + firstname
    + lastname
}


class School {
    + name
}

class Class {
    + letter
    + grade
    + year
}

Principal .-down-> Class : Creates >
Principal .-down-> Class : Adds pupils to the class
School "1" -- "many" Class : has >
Class "1" -- "1" Teacher: managed by >
Class "1" o-- "many" Pupil: contains >
@enduml