version: '3.1'

volumes:
  postgres_curricula:

services:
  curriculum:
    image: msschooltraining/curriculum-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres-curricula
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-curricula:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
  postgres-curricula:
    image: postgres
    volumes:
      - postgres_curricula:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: curricula
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"