version: '3.1'

volumes:
  postgres_curricula:

services:
  curriculum:
    image: dbelykyriba/curriculum-service:0.0.1
    depends_on:
      - postgres-curricula
    ports:
      - "8080:8080"
  postgres-curricula:
    image: postgres
    volumes:
      - postgres_curricula:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: curricula
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"