apiVersion: v1
kind: Service
metadata:
  name: gateway-app
  labels:
    app: gateway
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: gateway
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
      tier: frontend
  template:
    metadata:
      labels:
        app: gateway
        tier: frontend
    spec:
      containers:
        - image: msschooltraining/school-gateway:1.1.1
          name: gateway-app
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: APP_PORT
              value: "8180"
            - name: KC_ADDR
              value: keycloak-app
            - name: KC_PORT
              value: 80
          ports:
            - containerPort: 8180
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 80
            timeoutSeconds: 10
            failureThreshold: 10
      restartPolicy: Always
