apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
      tier: frontend
  template:
    metadata:
      labels:
        app: gateway
        tier: frontend
    spec:
      containers:
        - image: msschooltraining/school-gateway:1.1.3
          name: gateway-app
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: APP_PORT
              value: "8080"
            - name: KC_ADDR
              value: keycloak-app
            - name: KC_PORT
              value: "80"
            - name: KC_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: keystore_password
            - name: KC_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: key_password
            - name: KC_KEY_ALIAS
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: key_alias
            - name: USERCERVICE_URL
              value: usercervice
            - name: USERCERVICE_PORT
              value: "80"
            - name: SCHEDULESERVICE_URL
              value: schedule-service
            - name: SCHEDULESERVICE_PORT
              value: "80"
            - name: SCHOOLCLASSSERVICE_URL
              value: chool-class-service-app
            - name: SCHOOLCLASSSERVICE_PORT
              value: "80"
            - name: CURRICULUM_URL
              value: curriculum
            - name: CURRICULUM_PORT
              value: "80"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 80
            timeoutSeconds: 10
            failureThreshold: 10
      restartPolicy: Always
