apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak
spec:
  ports:
    - port: 5432
  selector:
    app: keycloak
    tier: postgreSQL
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  labels:
    app: keycloak
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      tier: postgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:10
          name: keycloakd-postgresql
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: user
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-pg-storage
      restartPolicy: Always
      volumes:
        - name: keycloak-pg-storage
          persistentVolumeClaim:
            claimName: keycloak-pv-claim
