apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app: keycloak
spec:
  ports:
    - port: 5432
  selector:
    app: keycloak
    tier: postgreSQL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  labels:
    app: keycloak
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: api/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:10
          name: keycloakd-postgresql
          resources: {}
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: zaq12wsx
            - name: POSTGRES_USER
              value: keycloak
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-pg-storage
      restartPolicy: Always
      volumes:
        - name: keycloak-pg-storage
          persistentVolumeClaim:
            claimName: keycloak-pv-claim
