apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
  labels:
    app: keycloak
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: keycloak
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
        tier: frontend
    spec:
      containers:
        - image: jboss/keycloak
          name: keycloak
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: DB_ADDR
              value: keycloak-db
            - name: DB_DATABASE
              value: keycloak
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyclock-db-secret
                  key: password
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keyclock-db-secret
                  key: user
            - name: DB_VENDOR
              value: POSTGRES
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyclock-db-secret
                  key: password
            - name: KEYCLOAK_USER
              value: admin
          args:
            - -b 0.0.0.0 --server-config=standalone.xml
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /config/
              name: keycloak-config
      restartPolicy: Always
      volumes:
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-pv-claim
