INSERT INTO SCHOOL_CLASS(GRADE, LETTER, YEAR)
VALUES (1, 'A', 2010);

INSERT INTO PUPIL(PUPIL_ID, FULL_NAME, CLASS_ID)
VALUES (1, 'Иванов', 1);

INSERT INTO PUPIL(PUPIL_ID, FULL_NAME, CLASS_ID)
VALUES (2, 'Петров', 1);

INSERT INTO PUPIL(PUPIL_ID, FULL_NAME, CLASS_ID)
VALUES (3, 'Сидоров', null);

INSERT INTO SCHOOL_CLASS(GRADE, LETTER, YEAR)
VALUES (2, 'Б', 2009);

