apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: curriculum
  name: curriculum
spec:
  type: NodePort
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: curriculum
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: curriculum
  name: curriculum
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: curriculum
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: curriculum
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: curriculum-db-secret
              key: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-curricula:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: curriculum-db-secret
              key: user-name
        image: msschooltraining/curriculum-service:0.0.1-SNAPSHOT
        name: curriculum
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 80
          timeoutSeconds: 10
          failureThreshold: 10