apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-curricula
  name: postgres-curricula
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres-curricula
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-curricula
  name: postgres-curricula
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-curricula
  name: postgres-curricula
spec:
  selector:
    matchLabels:
      io.kompose.service: postgres-curricula
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-curricula
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: curricula
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: curriculum-db-secret
              key: user-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: curriculum-db-secret
              key: password
        image: postgres
        name: postgres-curricula
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-curricula
      restartPolicy: Always
      volumes:
      - name: postgres-curricula
        persistentVolumeClaim:
          claimName: postgres-curricula
