version: '3.1'

networks:
  postgres:
    driver: bridge

volumes:
  postgres_curricula:
  pgadmin:

services:
  postgres-curricula:
    image: postgres
    volumes:
      - postgres_curricula:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: curricula
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - postgres
    ports:
      - "5433:5432"
  pgadmin: # management tool for DB
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    networks:
      - postgres
    ports:
      - 9098:80
    depends_on:
      - postgres-curricula