# Application
info.app:
  name: School Garteway Application
  description: School Garteway Application
  version: 1.1.1

# Logging
logging.level:
  org.springframework: INFO

# Server
server:
  port: ${APP_PORT:8080}
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/school.p12
#    key-store-password: zaq12wsx
#    key-alias: school

spring:
  freemarker:
    template-loader-path: classpath:/webapp/templates/
    suffix: .ftl
    enabled: true

# Keycloak
keycloak:
  realm: school
  auth-server-url: http://${KC_ADDR:keycloak}:${KC_PORT:8080}/auth
  resource: school-app
  cors: true
  use-resource-role-mappings: false
  credentials:
    jwt:
      client-keystore-file: "classpath:keystore/keystore.jks"
      client-keystore-type: "JKS"
      client-keystore-password": ${KC_KEYSTORE_PASSWORD}
      client-key-password: ${KC_KEY_PASSWORD}
      client-key-alias: ${KC_KEY_ALIAS:school-app}
      token-expiration": 10

# Zuul
zuul:
  routes:
    userservice:
      path: /userservice/**
      url: http://${USERCERVICE_URL:userservice-app}:${USERCERVICE_PORT:80}
      stripPrefix: true
    scheduleservice:
      path: /scheduleservice/**
      url: http://${SCHEDULESERVICE_URL:scheduleservice-app}:${SCHEDULESERVICE_PORT:80}
      stripPrefix: true
    schoolclassservice:
      path: /schoolclassservice/**
      url: http://${SCHOOLCLASSSERVICE_URL:schoolclassservice-app}:${SCHOOLCLASSSERVICE_PORT:80}
      stripPrefix: true
    curriculum:
      path: /curriculum/**
      url: http://${CURRICULUM_URL:curriculum-app}:${CURRICULUM_PORT:80}
      stripPrefix: true
