# Application
info.app:
  name: School Garteway Application
  description: School Garteway Application
  version: 1.1

# Logging
logging.level:
  org.springframework: DEBUG
  org.keycloak: DEBUG
  org.freemarker: DEBUG

# Server
server:
  port: 8180
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/school.p12
#    key-store-password: zaq12wsx
#    key-alias: school

spring:
  freemarker:
    template-loader-path: classpath:/webapp/templates/
    suffix: .ftl
    enabled: true

# Keycloak
keycloak:
  realm: school
  auth-server-url: http://${KC_ADDR:keycloak}:${KC_PORT:8080}/auth
  resource: school-app
  cors: true
  use-resource-role-mappings: false
  credentials:
    jwt:
      client-keystore-file: "classpath:keystore/keystore.jks"
      client-keystore-type: "JKS"
      client-keystore-password": "zaq12wsx"
      client-key-password: "zaq12wsx"
      client-key-alias: "school-app"
      token-expiration": 10

# Zuul
zuul:
  routes:
    google:
      path: /userservice/**
      url: http://userservice-app:80
      stripPrefix: true
