apiVersion: v1
kind: Service
metadata:
  name: userservice-app
  labels:
    app: userservice
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: userservice
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-app
  labels:
    app: userservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: userservice
        tier: backend
    spec:
      containers:
        - image: msschooltraining/user-service:1.0.1
          imagePullPolicy: IfNotPresent
          name: userservice-app
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: USERSERVICE_DB_HOST
              value: userservice-db
            - name: USERSERVICE_DB_PORT
              value: "3306"
            - name: USERSERVICE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: user-name
            - name: USERSERVICE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: db-name
            - name: USERSERVICE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: password
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 80
            timeoutSeconds: 10
            failureThreshold: 10