apiVersion: v1
kind: Service
metadata:
  name: userservice-db
  labels:
    app: userservice
spec:
  ports:
    - port: 3306
  selector:
    app: userservice
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userservice-db-pv-claim
  labels:
    app: userservice
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-db
  labels:
    app: userservice
spec:
  selector:
    matchLabels:
      app: userservice
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: userservice
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0.17
          name: userservice-mysql
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: user-name
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: db-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userservice-mysql-secret
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: userservice-db-pv-claim