version: '2'
services:
  database:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  school-class:
    build: .
    ports:
      - "8082:10000"
    environment:
      - DB_ADDRESS=database
      - DB_PORT=5432
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
volumes:
  postgres:
