version: '2'
services:
  database:
    volumes:
      - ./target/database:/opt/h2-data
    ports:
      - "81:81"
    image: oscarfonts/h2
    #exposes port internally in docker network for all other containers - no need (at least for now)
    #to expose it outside of the network
    expose:
      - "1521"
  school-class:
    build: .
    ports:
      - "8082:10000"
    environment:
      - H2_DB_ADDRESS=database
    depends_on:
      - database
