#server:
#  port: 8083
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: curriculum
  #datasource:
  #  initialization-mode: always
  #jpa:
  #  properties:
  #    javax:
  #      persistence:
  #        schema-generation:
  #          create-source: metadata
  #          scripts:
  #           action: create
  #           create-target: schema.sql
      #hibernate:
      #  dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:changelog.json