apiVersion: v1
kind: Service
metadata:
  name: school-curriculum-service-app
  labels:
    app: school-curriculum-service
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: school-curriculum-service
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-curriculum-service-app
  labels:
    app: school-curriculum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-curriculum-service
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: school-curriculum-service
        tier: backend
    spec:
      containers:
        - image: kyriba/school-curriculum-service:1.0.0
          imagePullPolicy: IfNotPresent
          name: school-curriculum-service-app
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://school-class-curriculum-db:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: dbuser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            timeoutSeconds: 10
            failureThreshold: 10
