apiVersion: v1
kind: Service
metadata:
  name: school-class-service-db
  labels:
    app: school-class-service
spec:
  ports:
    - port: 5432
  selector:
    app: school-class-service
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: school-class-service-db-pv-claim
  labels:
    app: school-class-service
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-class-service-db
  labels:
    app: school-class-service
spec:
  selector:
    matchLabels:
      app: school-class-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: school-class-service
        tier: postgres
    spec:
      containers:
        - image: postgres:12
          name: school-class-service-postgres
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: school-class-service-db-pv-claim