apiVersion: v1
kind: Service
metadata:
  name: school-class-service-app
  labels:
    app: school-class-service
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: school-class-service
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-class-service-app
  labels:
    app: school-class-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-class-service
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: school-class-service
        tier: backend
    spec:
      containers:
        - image: kyriba/school-class-service:1.0.0
          imagePullPolicy: IfNotPresent
          name: school-class-service-app
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
          env:
            - name: H2_DB_ADDRESS
              value: school-class-service-db
            - name: USERSERVICE_HOST
              value: userservice-app
          ports:
            - containerPort: 10000
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 10000
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 10000
            initialDelaySeconds: 80
            timeoutSeconds: 10
            failureThreshold: 10